# Lecture 08: Functions 

In [3]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

## Defining Functions 

**The Anatomy of a Function:**
    
```python
def functionname(Arguments_Parameters_Expressions_or_Values):     
    return return_expression
```

Example: Create a function that takes a numerical input and triples it: $\textsf{triple}(x)=3\,x$

In [4]:
def triple(x):
    return 3 * x

In [5]:
triple(3)

9

In [6]:
triple(3.0)

9.0

In [7]:
triple('ha')

'hahaha'

In [8]:
num = 4
triple(num) # triple(4)

12

In [9]:
triple(3 * num) # triple (3 * 4) = triple (12)

36

We can also assign a value to a name, and call the function on the name:

## Functions are Type-Agnostic  ## 
Try feeding it a float

In [10]:
np.arange(4)

array([0, 1, 2, 3])

In [11]:
triple(np.arange(4))

array([0, 3, 6, 9])

Try feeding it a string

Try feeding it an array

Try feeding it a table

### Discussion Question 
What does this function do? What kind of input does it  take? What output will it give? What's a reasonable name?


```python
def f(s):     
    return np.round(s / sum(s) * 100, 2)
```

TypeError: 'float' object is not iterable

Let's rename the function to what it does

In [13]:
def percent_of_total(s):
    return np.round(s/sum(s) * 100, 2)

In [14]:
first_four = make_array(1,2,3,4)
first_four

array([1, 2, 3, 4])

In [16]:
np.median(first_four)

2.5

In [15]:
percent_of_total(first_four)

array([ 10.,  20.,  30.,  40.])

### Functions Can Take Multiple Arguments ###

Example: Calculate the Hypotenuse Length of a Right Triangle


Pythagoras's Theorem: If $x$ and $y$ denote the lengths of the right-angle sides, then the hypotenuse length $h$ satisfies:

$$ h^2 = x^2 + y^2 \qquad \text{which implies}\qquad \hspace{20 pt} h = \sqrt{ x^2 + y^2 } $$

We could've typed the body all in one line. Do you find this more readable or less readable than the original version?

### Example: A function that takes the year of birth of a person and produces their age in years. ###

Now add some bells and whistles:  Take person's name and year of birth (two arguments). Produce a sentence that states how old they are.

-----
Back to slides

---

## Apply ##

In [ ]:
staff = Table().with_columns(
    'Person', make_array('Jim', 'Pam', 'Michael', 'Creed'),
    'Birth Year', make_array(1985, 1988, 1967, 1904)
)
staff

- we could run the age function on every element of the birth year column  
- and then create an array. 

In [ ]:
age(staff.column('Birth Year').item(0))

Let's instead `apply` the `age` and `name_and_age` function to a column