# Lecture 08: Functions 

In [2]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

## Defining Functions 

**The Anatomy of a Function:**
    
```python
def functionname(Arguments_Parameters_Expressions_or_Values):     
    return return_expression
```

Example: Create a function that takes a numerical input and triples it: $\textsf{triple}(x)=3\,x$

In [3]:
def triple(x):
    return 3 * x

In [4]:
triple(3)

9

In [5]:
triple(3.0)

9.0

In [6]:
triple('ha')

'hahaha'

In [7]:
num = 4
triple(num) # triple(4)

12

In [8]:
triple(3 * num) # triple (3 * 4) = triple (12)

36

We can also assign a value to a name, and call the function on the name:

## Functions are Type-Agnostic  ## 
Try feeding it a float

In [9]:
np.arange(4)

array([0, 1, 2, 3])

In [10]:
triple(np.arange(4))

array([0, 3, 6, 9])

Try feeding it a string

Try feeding it an array

Try feeding it a table

### Discussion Question 
What does this function do? What kind of input does it  take? What output will it give? What's a reasonable name?


```python
def f(s):     
    return np.round(s / sum(s) * 100, 2)
```

Let's rename the function to what it does

In [11]:
def percent_of_total(s):
    return np.round(s/sum(s) * 100, 2)

In [12]:
first_four = make_array(1,2,3,4)
first_four

array([1, 2, 3, 4])

In [13]:
first_four / sum(first_four) 
# take each element of my array and divide by sum of array
# (1, 2, 3, 4) / 10 = (1/10, 2/10, 3/10, 4/10) = (0.1, 0.2, 0.3, 0.4)

array([ 0.1,  0.2,  0.3,  0.4])

In [19]:
first_four / sum(first_four) * 100
np.round(first_four / sum(first_four) * 100, 2)

array([ 10.,  20.,  30.,  40.])

In [14]:
np.median(first_four)

2.5

In [15]:
percent_of_total(first_four)

array([ 10.,  20.,  30.,  40.])

In [20]:
max(2, 4)

4

### Functions Can Take Multiple Arguments ###

Example: Calculate the Hypotenuse Length of a Right Triangle


Pythagoras's Theorem: If $x$ and $y$ denote the lengths of the right-angle sides, then the hypotenuse length $h$ satisfies:

$$ h^2 = x^2 + y^2 \qquad \text{which implies}\qquad \hspace{20 pt} h = \sqrt{ x^2 + y^2 } $$

We could've typed the body all in one line. Do you find this more readable or less readable than the original version?

In [21]:
def hypotenuse(x,y): # function header, needs to end with colon :
    # this is our function body
    # to do stuff with our inputs x and y
    h_squared = x**2 + y**2 # x^2 + y^2
    h = np.sqrt(h_squared) # square root of x^2 + y^2
    return h

In [22]:
1 ** 2 + 1 ** 2

2

In [23]:
np.sqrt(2)

1.4142135623730951

In [24]:
hypotenuse(1,1)

1.4142135623730951

In [25]:
np.sqrt(2 ** 2 + 2 ** 2)

2.8284271247461903

In [26]:
hypotenuse(2, 2)

2.8284271247461903

### Example: A function that takes the year of birth of a person and produces their age in years. ###

In [ ]:
#2024  - your birth year
# input: your birth year
# output: 2024 - your birth year

In [34]:
def age(year): # function header, one input: year
    what_is_your_age = 2024 - year
    return "You are " + str(what_is_your_age) + " year(s) old."

In [36]:
def age2(year): # function header, one input: year
    what_is_your_age = 2024 - year
    print("Your Age: ")
    return what_is_your_age

In [37]:
age(2004)

'You are 20 year(s) old.'

In [38]:
age2(2004)

Your Age: 


20

In [41]:
def age(year): # function header, one input: year
    what_is_your_age = 2024 - year
    return what_is_your_age # return one variable

Now add some bells and whistles:  Take person's name and year of birth (two arguments). Produce a sentence that states how old they are.

In [44]:
def name_and_age(name, year): # define our function with more than one argument (input)
    your_age = age(year) # call on another function, within a function
    return name + ' is ' + str(your_age) + ' years old.' # return string statement, with concatenation

In [45]:
name_and_age('Vanessa', 2004)

'Vanessa is 20 years old.'

-----
Back to slides

---

## Apply ##

In [16]:
staff = Table().with_columns(
    'Person', make_array('Jim', 'Pam', 'Michael', 'Creed'),
    'Birth Year', make_array(1985, 1988, 1967, 1904)
)
staff

Person  | Birth Year
Jim     | 1985
Pam     | 1988
Michael | 1967
Creed   | 1904

- we could run the age function on every element of the birth year column  
- and then create an array. 

In [17]:
age(staff.column('Birth Year').item(0))

NameError: name 'age' is not defined

Let's instead `apply` the `age` and `name_and_age` function to a column