In [47]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

# Recap

## Arithmetic on numbers

In [48]:
( 1 + 4) / 5 # notice i am performing sum and then division with integers
# and my output is a float
# anything with a decimal value, is a float data type

1.0

In [49]:
type(( 1 + 4) / 5)

float

In [50]:
type(5)

int

In [51]:
type( 1 + 4)

int

In [52]:
2 ** 4

16

In [53]:
3 * 4

12

## Built-in functions

In [54]:
abs(5)

5

In [55]:
abs(-5)

5

In [56]:
help(abs)

Help on built-in function abs in module builtins:

abs(x, /)
    Return the absolute value of the argument.



In [57]:
abs?

Signature: abs(x, /)
Docstring: Return the absolute value of the argument.
Type:      builtin_function_or_method

In [58]:
min(4, -4 )

-4

## Variables
- Create
- Use
- Overwrite

In [59]:
a = 3

In [60]:
a = 5

In [61]:
a

5

In [62]:
a + a

10

In [63]:
a = a + a # assigning value to a

In [64]:
a # calling on a, to display its output

10

## Errors
- undefined name
- unsupported operand
- wrong number of arguments
- invalid keyword argument
- division by zero

In [65]:
a

10

In [66]:
b

NameError: name 'b' is not defined

In [ ]:
animal = " dog " 

In [ ]:
1 + animal

In [ ]:
'my' + animal

In [ ]:
abs(4, 5)

In [ ]:
help(abs)

In [ ]:
round(number=1.2435, ndigits=1) # rounding 1.2435 to 1 decimal place

In [ ]:
round(number=1.2435, ndigits=1.2435) 

In [ ]:
round?

In [ ]:
round(number=1.2435, ndigits=0) 

In [ ]:
round(number=1.2435, ndigits=-1) 

In [ ]:
round(number=9.2435, ndigits=-1) 

In [ ]:
1/0

## Types 
- int
- float
- string/text
- bool
- table `Table.read_table('data/skyscrapers.csv')`
- `type()` function

In [ ]:
type(a)

In [ ]:
a == 10 # check for equality, does a equal 10?
# checking for equality, not assigning value

In [ ]:
type(a == 10)

In [ ]:
print(a != 10) # checking if a does not equal to 10, False
print(a != 11) # checking if a does not equal to 11, True
# Note, we are NOT assigning value here. we are checking for inequality

In [ ]:
a >= 10

**Question:** what will `type(int(float('3.14159')))` return?

In [ ]:
type(float('3.14159')) # takes a string, which contains a float value
# and converts to a float

In [ ]:
int(float('3.14159')) # converting float to an int
# cutting off decimal places


In [ ]:
type(int(float('3.14159'))) # checking int for data type

--- 
Back to slides

---

# Arrays
Arrays are ordered "lists" of elements that can be directly accessed by location.

## Making Arrays
**Exercise**: Make an array of 4 numbers using `make_array()`

In [67]:
make_array(1, 2, 3, 4)
# if we get an error about any datascience function or Table operation that isn't defined
# we know to re-run our first cell in our notebook
# that imports the datascience package, so we can access the functions within

array([1, 2, 3, 4])

**Exercise:** Arrays can be any type. Make an array of `Strings` called `string_array`:

In [69]:
string_array = make_array('my', "cat's", 'name','is','maliki') # what is your pet's name?
string_array

array(['my', "cat's", 'name', 'is', 'maliki'],
      dtype='<U6')


**Exercise:** Mixing types (Strings, Numbers, Booleans).  Make an array of multiple types:

In [70]:
make_array('cat', 1, True) # python wants the elements in our arrays to have the same data types
# here we have a string and a int and a boolean value
# converted all elements into strings

array(['cat', '1', 'True'],
      dtype='<U21')

In [71]:
make_array(1, 1.0, True)

array([ 1.,  1.,  1.])

In [72]:
make_array(1, '1.5', False)

array(['1', '1.5', 'False'],
      dtype='<U21')

**Question**: What is the type of `weird_array`?

In [74]:
weird_array = make_array(1, 1.0, True)
type(weird_array)

numpy.ndarray

In [76]:
np.ndarray?

Init signature: np.ndarray(self, /, *args, **kwargs)
Docstring:     
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dtype : data-type, optional
    Any object that can be interpreted as a numpy data type.
buffer : object exposing buffer int

## Simple Arithmetics on Arrays

Assume, we have:
- an array of heights given in inches 
- an array of heights given in feet
- an array of masses in kg
    
We want to:
- convert the heights to centimeters (1 ft = 12 in; 1 in = 2.54 cm)
- calculate avg height
    - manuall
    - using np function
- convert back to inch and ft
- add an offset
- calculate BMI
    - $BMI = m/h^2$ 
    - $[m] = kg$
    - $[h]=m$

In [77]:
heights_inches = make_array(8, 6, 3, 5) #inches portion of height stored here
heights_feet = make_array(5, 5, 5, 6) # feet portion of height stored here
mass_kg = make_array(68, 75 ,67, 80)

In [78]:
# convert heights to cm
heights_inches_total = heights_feet * 12 + heights_inches
heights_inches_total

array([68, 66, 63, 77])

In [80]:
# calculate average height
sum(heights_inches_total)/4

68.5

In [82]:
# calculate average height
sum(heights_inches_total)/len(heights_inches_total)
len(heights_inches_total)

4

In [85]:
# calculate average height
np.mean(heights_inches_total) # np.mean takes the average of the array passed through

68.5

In [86]:
np.floor(heights_inches_total / 12)

array([ 5.,  5.,  5.,  6.])

In [87]:
np.floor?

Call signature:  np.floor(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'floor'>
File:            /opt/conda/lib/python3.11/site-packages/numpy/__init__.py
Docstring:      
floor(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Return the floor of the input, element-wise.

The floor of the scalar `x` is the largest integer `i`, such that
`i <= x`.  It is often denoted as :math:`\lfloor x \rfloor`.

Parameters
----------
x : array_like
    Input data.
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, t

In [91]:
heights_m = heights_inches_total * 2.54 / 100
heights_m

array([ 1.7272,  1.6764,  1.6002,  1.9558])

In [92]:
# bmi
bmi = mass_kg / heights_m**2
bmi

array([ 22.79416324,  26.6873812 ,  26.16533326,  20.91419261])

### Aggregation Operations

You will often need to compute summaries of an array like the `sum`, `max`, or the `min`.  These are all **member functions** of an array.  Here is the documentation on all the **[member functions](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html)** for arrays.

**Exercise:** Use the `sum`, `min`, `mean`, and `max` operations to summarize the cool numbers array.

In [94]:
np.sum(heights_m) / 4 # average height in m

1.7399

In [96]:
np.max(heights_m)

1.9558000000000002

In [97]:
np.min(heights_m)

1.6002000000000001

## Ranges
We use ranges to make arrays of number sequence easily.  The numpy `np.arange(start, stop, step)` function produce an array starting at `start` and ending *before* `stop`, in increments of `step`.

In [98]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)
    
    Return evenly spaced values within a given interval.
    
    ``arange`` can be called with a varying number of positional arguments:
    
    * ``arange(stop)``: Values are generated within the half-open interval
      ``[0, stop)`` (in other words, the interval including `start` but
      excluding `stop`).
    * ``arange(start, stop)``: Values are generated within the half-open
      interval ``[start, stop)``.
    * ``arange(start, stop, step)`` Values are generated within the half-open
      interval ``[start, stop)``, with spacing between values given by
      ``step``.
    
    For integer arguments the function is roughly equivalent to the Python
    built-in :py:class:`range`, but returns an ndarray rather than a ``range``
    instance.
    
    When using a non-integer step, such as 0.1, it is often better to use
    `numpy.linspace`.
    
    S

**Exercise:** Make an array of the nubmers 0 through 6:

In [99]:
make_array(0, 1, 2, 3, 4, 5, 6)

array([0, 1, 2, 3, 4, 5, 6])

Can we writer it shorter?

In [100]:
np.arange(0,7, 1)

array([0, 1, 2, 3, 4, 5, 6])

In [101]:
np.arange(0,7)

array([0, 1, 2, 3, 4, 5, 6])

In [102]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

**Question 1:** can we create an array from 0 to 100, including 100, with a step increase of 10?

In [105]:
print(np.arange(0, 110, 10))
print(np.arange(0, 101, 10))

[  0  10  20  30  40  50  60  70  80  90 100]
[  0  10  20  30  40  50  60  70  80  90 100]


**Question 2:** can we create an array from 100 to 200, not including 200, with a step increase of 10?

In [107]:
np.arange(100,200,10)

array([100, 110, 120, 130, 140, 150, 160, 170, 180, 190])

**Challenge question:** can we create an array that *decreases* from 10 to 0 (including both 10 and 0)?

In [108]:
np.arange(10,-1,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [109]:
np.arange(start=10,stop=-1,step=-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [110]:
np.arange(stop=-1, start=10, step=-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [111]:
np.arange?

Docstring:
arange([start,] stop[, step,], dtype=None, *, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The interva

**Exercise:** What will the following produce:

```python
np.arange(40, -1, -5) 
```

## Accessing Elements

For this exercise lets start with this array of strings.

**Question:** how do we get the largest item in the `heights` array. Hint: use `np.sort()`

In [114]:
max(heights_m)

1.9558000000000002

In [116]:
np.sort(heights_m).item(3) # grabbed the item in position 3, which was the tallest height
# after we sorted

1.9558000000000002

In [118]:
string_array = make_array("cat", "dog", "bird")
string_array.item(0) #cat
string_array.item(1) #dog
string_array.item(2) # bird

'bird'

In [119]:
np.sort(string_array)

array(['bird', 'cat', 'dog'],
      dtype='<U4')

In [120]:
1 < 2 < 3

True

In [121]:
'a' < 'b' < 'c'


True

You can use `array_name.item( NUMBER )` to get an element from an array.

**Exercise:** What will the following expression return?

```python
string_array.item(1)
```

In [123]:
string_array.item(1)

'dog'

**Bonus!** This is called **array indexing**.  There is a shorter "equivalent" syntax that people will often use. However, for this class you only need to know about `.item()`.

```python
string_array[ INDEX ]
```

In [122]:
string_array[1]

'dog'

**Exercise:** Use the `len` function to determine the length of the string array.

Arrays also have a **member variable** `array_name.size` that contains the size of the array.  

**Exercise:** Use the size **member variable** to check the size of the array:

In [124]:
string_array.size

3

In [128]:
# default nature of sort is smallest to greatest, ascending OR descending = False
np.sort(string_array, descending = True)

TypeError: sort() got an unexpected keyword argument 'descending'

In [129]:
np.sort?

Signature:       np.sort(a, axis=-1, kind=None, order=None)
Call signature:  np.sort(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function sort at 0x7f646056e480>
File:            /opt/conda/lib/python3.11/site-packages/numpy/core/fromnumeric.py
Docstring:      
Return a sorted copy of an array.

Parameters
----------
a : array_like
    Array to be sorted.
axis : int or None, optional
    Axis along which to sort. If None, the array is flattened before
    sorting. The default is -1, which sorts along the last axis.
kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
    Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
    and 'mergesort' use timsort or radix sort under the covers and, in general,
    the actual implementation will vary with data type. The 'mergesort' option
    is retained for backwards compatibility.

    .. versionchanged:: 1.15.0.
       The 'stable' option was added.

order : str or list of str, o


## Common Bugs

**Exercise:** What happens if we run the following:

```python
a = make_array(0,1,2,3)
bigger_array = make_array(1,2,3,4,5)
a * bigger_array
```

In [131]:
a = make_array(0,1,2,3)
print(a)
bigger_array = make_array(1,2,3,4,5)
print(bigger_array)
a * bigger_array

[0 1 2 3]
[1 2 3 4 5]


ValueError: operands could not be broadcast together with shapes (4,) (5,) 

**Exercise:** What happens if I run the following:

```python
uhoh = make_array(0,1,2,3)
a / uhoh
```

**Exercise:** What happens if I run the following:

```python
a.item(4)
```

**Exercise:** What happens if I run the following:

```python
a.item(-1)
```

# Tables
Tables are Made of Arrays

We are covering arrays because this is the mathematical object that is returned when we work on specific columns of a table. Here we load a table of NBA salaries from a local file `nba_salaries.csv`.

In [ ]:
nba = Table.read_table('data/nba_salaries.csv')
nba

Let's focus on the **Golden State Warriors**.

**Exercise:** Use the `my_table.where` function to select the rows where team is the `"Golden State Warriors"`.

We can also select columns by name. 

**Exercise**: Make a table with just the `"name"` and `"salary"` columns. 


**Exercise:** Compute the average average salary of the warriors.  Which of the following works?

*Option (A):*
```python
warriors.mean()
```

*Option (B):*
```python
warriors.select("salary").mean()
```

*Option (C):*
```python
warriors.column("salary").mean()
```

**Exercise:** Would the following work?

```python
np.average(warriors.select("salary"))
```

In [ ]:
np.average(warriors.select("salary"))

Why?

**Exercise:** Use `np.average` to compute the average salary of the Warriors:

<details><summary>Solution</summary>
   
```python
np.average(warriors.column("salary"))
```
    
</details></br></br>

**Exercise:** Compute the difference in the average salaries of the warriors and the `"Los Angeles Lakers"`.

<details><summary>Solution</summary>
   
```python
lakers = nba.where('team', 'Los Angeles Lakers')
warriors.column('salary').mean() - lakers.column('salary').mean()
```
</details>

## Creating a Table from Arrays

Let's start with an array of street names.

In [ ]:
streets = make_array('Embarcadero De Norte', 
                     'Embarcadero De Mar', 
                     'Camino Pescadero', 
                     'Camino Del Sur')
streets

We can make an empty table (no rows, no columns, no problems ...).

The `Table()` function makes an empty table.

In [ ]:
empty_table = Table()
empty_table

**Exercise:** Check that the empty table has 0 rows and 0 columns
 using the `num_rows` and `num_columns` attribute

**Exercise:** Use the `table.with_column` function to add a column to the table and save the new table as `IV`.

**Exercise:** What is the output of:
```python
empty_table.with_column("Streets", streets)
empty_table.num_columns
```

**Exercise:** Can you do the same thing without using `empty_table`? Hint: use `Table()` directly.

**Exercise:** Extend the IV table to include the blocks from campus (use `np.arange`). ([map](https://goo.gl/maps/2pnJvxSWfmNaKJvUA))

**Exercise:** Build the entire table with blocks from campus in one call to the `Table.with_columns()` function.

---
Back to slides

---

# Case Study: Understanding the [W. E. B. Du Bois](https://en.wikipedia.org/wiki/W._E._B._Du_Bois) Visualization

![Picture from Wikipedia](https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/W.E.B._Du_Bois_by_James_E._Purdy%2C_1907_%28cropped%29.jpg/167px-W.E.B._Du_Bois_by_James_E._Purdy%2C_1907_%28cropped%29.jpg)

**From Wikipedia:**  *William Edward Burghardt Du Bois (/djuːˈbɔɪs/ dew-BOYSS;[1][2] February 23, 1868 – August 27, 1963) was an American sociologist, socialist, historian, and Pan-Africanist civil rights activist. Born in Great Barrington, Massachusetts, Du Bois grew up in a relatively tolerant and integrated community. After completing graduate work at the University of Berlin and Harvard University, where he was the first African American to earn a doctorate, he became a professor of history, sociology, and economics at Atlanta University. Du Bois was one of the founders of the National Association for the Advancement of Colored People (NAACP) in 1909.*

For more context on the visualization in lecture checkout [Du Bois’ Data Portraits Tell A Story About Black Life In Georgia And Beyond](https://www.wabe.org/du-bois-data-portraits/)



In [ ]:
du_bois = Table.read_table('data/du_bois.csv')
du_bois

**Exercise:** Compute the amount of money spent on food and add it to the table and add it to the table as `"FOOD $"`:

**Exercise:** Use the table functions we learned this week to find the income bracket ("class") that spent the most money on rent.

**Bonus:** use the `set_format()` function to display the shares as percentages (using the `PercentFormatter`)